# Generated by Django 4.2.3 on 2023-08-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contactinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("mail", models.EmailField(max_length=50)),
                ("contact", models.IntegerField()),
                ("subject", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
